### ISSUE TITLE
自定义预加载

### ISSUE THREAD

**Issue by ed29** [mudkipme/mediawiki-lazyload#2]
Hi：

我的 mediawiki 放在国外的共享空间，网络延迟有点多，图片加载因此也有点延迟，所以我想预加载多一～两屏的图片，不然滚屏拉下去的时候还要等，请问怎么实现？能修改一下里面哪个值吗？

**Comment by mudkipme** [comment]
可以修改 [modules/lazyload.js](https://github.com/mudkipme/mediawiki-lazyload/blob/master/modules/lazyload.js) 中 `threshold: 50` 这里（表示预加载的像素距离）

**Comment by ed29** [comment]
好的，谢谢
